import { useMemo, useState } from "react";
import { analyzeResult, formatSeconds } from "../workspace/analyzeResult.js";
import { ResultChart, ResultTable } from "../workspace/ResultView.jsx";
import SqlBlock from "../workspace/SqlBlock.jsx";

function when(iso) {
  return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function BoardCard({ card, onRefresh, onRemove, refreshing, error }) {
  const [showSql, setShowSql] = useState(false);
  const analysis = useMemo(() => analyzeResult(card.rows), [card.rows]);
  const kpis = analysis.kpis.slice(0, 2);
  const action = "rounded-md px-2 py-1 text-xs text-zinc-400 hover:bg-raised hover:text-zinc-200 disabled:opacity-40";

  return (
    <article className="flex flex-col rounded-xl border border-line bg-panel p-4">
      <header className="flex items-start gap-3">
        <div className="min-w-0 flex-1">
          <h3 className="font-medium text-white">{card.question}</h3>
          <p className="mt-0.5 text-xs text-zinc-500">
            {refreshing ? "Refreshing…" : `${card.refreshedAt ? "Refreshed" : "Pinned"} ${when(card.refreshedAt || card.pinnedAt)}`}
            {" · "}{card.execution?.totalRows?.toLocaleString("en-US")} rows · {formatSeconds(card.execution?.seconds)}
          </p>
        </div>
        <div className="flex shrink-0 gap-1">
          <button type="button" className={action} onClick={() => onRefresh(card)} disabled={refreshing}>Refresh</button>
          <button type="button" className={action} onClick={() => setShowSql((v) => !v)} aria-expanded={showSql}>SQL</button>
          {onRemove && <button type="button" className={action} onClick={() => onRemove(card.id)} aria-label={`Remove "${card.question}"`}>Remove</button>}
        </div>
      </header>

      {error && <p role="alert" className="mt-3 text-sm text-rose-300">{error}</p>}

      {kpis.length > 0 && (
        <dl className="mt-4 grid grid-cols-2 gap-3">
          {kpis.map((k) => (
            <div key={k.title}>
              <dt className="text-xs text-zinc-500">{k.title}</dt>
              <dd className="text-xl font-semibold tracking-tight text-white tabular-nums">{k.value}</dd>
              {k.detail && <dd className="truncate text-xs text-zinc-500" title={k.detail}>{k.detail}</dd>}
            </div>
          ))}
        </dl>
      )}

      <div className={`mt-4 ${refreshing ? "opacity-50" : ""}`}>
        {analysis.chart.kind !== "none" ? (
          <ResultChart chart={analysis.chart} compact bare />
        ) : (
          <ResultTable rows={card.rows} totalRows={card.execution?.totalRows ?? card.rows.length} maxHeight="max-h-60" />
        )}
      </div>

      {showSql && <SqlBlock sql={card.sql} className="mt-4" />}
    </article>
  );
}

export default function Board({ board, onGoToAsk }) {
  const { pins, examples, unpin, refresh, refreshing, errors, persisted } = board;

  return (
    <div className="mx-auto max-w-[1180px] p-4 md:p-6">
      <h1 className="text-2xl font-semibold tracking-tight text-white">Board</h1>
      <p className="mt-1 max-w-2xl text-sm text-zinc-400">
        Answers you pin from Ask are kept in this browser only. Refresh re-runs a card's SQL live on BigQuery.
      </p>
      {!persisted && <p className="mt-2 text-sm text-amber-300">This browser isn't allowing the page to save, so pins last until you close the tab.</p>}

      <section className="mt-8" aria-labelledby="pins-heading">
        <h2 id="pins-heading" className="text-sm font-medium text-zinc-300">Your pins{pins.length ? ` (${pins.length})` : ""}</h2>
        {pins.length === 0 ? (
          <div className="mt-3 rounded-xl border border-dashed border-line p-6 text-sm text-zinc-400">
            Nothing pinned yet. Ask a question, then use <span className="text-zinc-200">Pin to board</span> on the answer.
            <button type="button" onClick={onGoToAsk} className="ml-3 rounded-md bg-emerald-400 px-3 py-1.5 font-medium text-zinc-950">Go to Ask</button>
          </div>
        ) : (
          <div className="mt-3 grid gap-4 lg:grid-cols-2">
            {pins.map((card) => (
              <BoardCard key={card.id} card={card} onRefresh={refresh} onRemove={unpin} refreshing={refreshing[card.id]} error={errors[card.id]} />
            ))}
          </div>
        )}
      </section>

      <section className="mt-10" aria-labelledby="examples-heading">
        <h2 id="examples-heading" className="text-sm font-medium text-zinc-300">Example board</h2>
        <p className="mt-0.5 text-xs text-zinc-500">Four answers generated by this app's pipeline. Refresh any card to run it again.</p>
        <div className="mt-3 grid gap-4 lg:grid-cols-2">
          {examples.map((card) => (
            <BoardCard key={card.id} card={card} onRefresh={refresh} refreshing={refreshing[card.id]} error={errors[card.id]} />
          ))}
        </div>
      </section>
    </div>
  );
}
